models:
  - name: "claude-3-haiku-short"
    provider: "anthropic"
    api_key: "${ANTHROPIC_API_KEY}"
    base_url: "https://api.anthropic.com"
    prompt:
      k: 4
      n: 2000
      m: 500
      p: 3000
      include_previous_speeches: False
      elements:
        - "prompts/json/opening-instructions.txt"
        - "prompts/json/dqi-categories.txt"
        - "prompts/json/json-schema.txt"
        - "prompts/json/example1-json.txt"
        - "prompts/json/closing-instructions.txt"
    model_params:
      model: "claude-3-haiku-20240307"
      max_tokens: 4000
      temperature: 0.7
      top_p: 1
      preload_str: "Here is your requested JSON:\n{"
      prepend_str: "{"

  - name: "groq-mixtral"
    provider: "groq"
    api_key: "${GROQ_API_KEY}"
    base_url: "https://api.groq.com/openai/v1"
    prompt:
      k: 4
      n: 2000
      m: 500
      p: 3000
      include_previous_speeches: False
      elements:
        - "prompts/json/opening-instructions.txt"
        - "prompts/json/dqi-categories.txt"
        - "prompts/json/json-schema.txt"
        - "prompts/json/example1-json.txt"
        - "prompts/json/closing-instructions.txt"
    model_params:
      model: "mixtral-8x7b-32768"
      max_tokens: 4000
      temperature: 0.7
      top_p: 1
      preload_str: "Here is your requested JSON:\n{"
      prepend_str: "{"

  - name: "groq-llama3-8b"
    provider: "groq"
    api_key: "${GROQ_API_KEY}"
    base_url: "https://api.groq.com/openai/v1"
    prompt:
      k: 4
      n: 2000
      m: 500
      p: 3000
      include_previous_speeches: False
      elements:
        - "prompts/json/opening-instructions.txt"
        - "prompts/json/dqi-categories.txt"
        - "prompts/json/json-schema.txt"
        - "prompts/json/example1-json.txt"
        - "prompts/json/closing-instructions.txt"
    model_params:
      model: "llama3-8b-8192"
      max_tokens: 4000
      temperature: 0.7
      top_p: 1
      preload_str: "Here is your requested JSON:\n{"
      prepend_str: "{"

  - name: "groq-llama3-70b"
    provider: "groq"
    api_key: "${GROQ_API_KEY}"
    base_url: "https://api.groq.com/openai/v1"
    prompt:
      k: 4
      n: 2000
      m: 500
      p: 1000
      include_previous_speeches: False
      elements:
        - "prompts/json/opening-instructions.txt"
        - "prompts/json/dqi-categories.txt"
        - "prompts/json/json-schema.txt"
        - "prompts/json/example1-json.txt"
        - "prompts/json/closing-instructions.txt"
    model_params:
      model: "llama3-70b-8192"
      max_tokens: 4000
      temperature: 0.7
      top_p: 1
      preload_str: "The capital of Paris is:"
      prepend_str: "Howdy"
      # preload_str: "Here is your requested JSON:\n{"
      # prepend_str: "{"

  - name: "groq-gemma2-9b"
    provider: "groq"
    api_key: "${GROQ_API_KEY}"
    base_url: "https://api.groq.com/openai/v1"
    prompt:
      k: 4
      n: 2000
      m: 500
      p: 3000
      include_previous_speeches: False
      elements:
        - "prompts/json/opening-instructions.txt"
        - "prompts/json/dqi-categories.txt"
        - "prompts/json/json-schema.txt"
        - "prompts/json/example1-json.txt"
        - "prompts/json/closing-instructions.txt"
    model_params:
      model: "gemma2-9b-it"
      max_tokens: 4000
      temperature: 0.7
      top_p: 1
      preload_str: "Here is your requested JSON:\n{"
      prepend_str: "{"


  - name: "gpt-3.5-turbo-long"
    provider: "openai"
    api_key: "${OPENAI_API_KEY}"
    base_url: "https://api.openai.com/v1"
    prompt:
      elements:
        - "prompts/json/opening-instructions.txt"
        - "prompts/json/dqi-categories.txt"
        - "prompts/json/dqi-theory.txt"
        - "prompts/json/json-schema.txt"
        - "prompts/json/example1-json.txt"
        - "prompts/json/example2-json.txt"
        - "prompts/json/closing-instructions.txt"
      include_previous_speeches: True
      k: 4
      n: 5000
      m: 1000
      p: 10000
    model_params:
      model: "gpt-3.5-turbo-0125"
      max_tokens: 4000
      temperature: 0.7
      top_p: 1
      preload_str: "Here is your requested JSON:\n{"
      prepend_str: "{"

  - name: "gpt-3.5-turbo-short"
    provider: "openai"
    api_key: "${OPENAI_API_KEY}"
    base_url: "https://api.openai.com/v1"
    prompt:
      k: 4
      n: 2000
      m: 500
      p: 3000
      include_previous_speeches: False
      elements:
        - "prompts/json/opening-instructions.txt"
        - "prompts/json/dqi-categories.txt"
        - "prompts/json/json-schema.txt"
        - "prompts/json/example1-json.txt"
        - "prompts/json/closing-instructions.txt"
    model_params:
      model: "gpt-3.5-turbo-0125"
      max_tokens: 4000
      temperature: 0.7
      top_p: 1
      preload_str: "Here is your requested JSON:\n{"
      prepend_str: "{"
